bcton – HASTY
bcton Interface
3 statements
Source File
public interface bcton
Convert bit-string to number (real and integer, bit-string to number type casting).
Calls
Called By
Module Procedures
bctor_R8P bctor_R4P bctoi_I8P bctoi_I4P bctoi_I2P bctoi_I1P
Module Procedures
private elemental function bctor_R8P(bstr, knd) result(n)
Convert bit-string to real.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
real(kind=R8P), intent(in) :: knd
Number kind.
Return Value real(kind=R8P)
Number returned.
private elemental function bctor_R4P(bstr, knd) result(n)
Convert bit-string to real.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
real(kind=R4P), intent(in) :: knd
Number kind.
Return Value real(kind=R4P)
Number returned.
private elemental function bctoi_I8P(bstr, knd) result(n)
Convert bit-string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I8P), intent(in) :: knd
Number kind.
Return Value integer(kind=I8P)
Number returned.
private elemental function bctoi_I4P(bstr, knd) result(n)
Convert bit-string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I4P), intent(in) :: knd
Number kind.
Return Value integer(kind=I4P)
Number returned.
private elemental function bctoi_I2P(bstr, knd) result(n)
Convert bit-string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I2P), intent(in) :: knd
Number kind.
Return Value integer(kind=I2P)
Number returned.
private elemental function bctoi_I1P(bstr, knd) result(n)
Convert bit-string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I1P), intent(in) :: knd
Number kind.
Return Value integer(kind=I1P)
Number returned.
All Procedures
add_clone add_clone add_id add_pointer add_pointer allocate_members assert_close_r32 assert_close_r32_1 assert_close_r64 assert_close_r64_1 assert_equal_i16 assert_equal_i16_1 assert_equal_i32 assert_equal_i32_1 assert_equal_i64 assert_equal_i64_1 assert_equal_i8 assert_equal_i8_1 assert_equal_l assert_equal_l_1 assert_equal_r32 assert_equal_r32_1 assert_equal_r64 assert_equal_r64_1 assert_positive_i16 assert_positive_i16_1 assert_positive_i32 assert_positive_i32_1 assert_positive_i64 assert_positive_i64_1 assert_positive_i8 assert_positive_i8_1 assert_positive_r32 assert_positive_r32_1 assert_positive_r64 assert_positive_r64_1 bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian check_type compact_real_string creator ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P destroy destroy destroy destroy destroy destroy_content destroy_dictionary_node destroy_key dictionary_len digit digit_I1 digit_I2 digit_I4 digit_I8 finalize finalize finalize find_next_prime get_bucket_image_indexes get_clone get_clone get_pointer get_pointer get_pointer has_key has_key has_key hash hash hash_string hash_table_finalize hash_table_len id ids ids init initialize initialize initialize is_equal is_equal is_filled is_homogeneous is_initialized is_key_allowed is_prime iterator_max iterator_max key_base len len loop node penf_init penf_print print print_content_iterator print_content_iterator print_keys print_keys remove remove remove_by_pointer remove_id set set_buckets_number set_caf_dimensions set_clone set_homogeneous set_pointer str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P stringify stringify strz strz_I1P strz_I2P strz_I4P strz_I8P synchronize_images test_assert_equal test_assert_equal test_assert_equal test_dictionary_finalize tests_non_captured tests_non_captured traverse traverse traverse_iterator
Call graph
bcton calls bctoi_i2p, bctoi_i1p, bctor_r4p, bctoi_i8p, bctoi_i4p, bctor_r8p
bctoi_i2p calls str
bctoi_i1p calls str
bctor_r4p calls str
bctoi_i8p calls str
bctoi_i4p calls str
bctor_r8p calls str
str calls strf_r4p, str_i2p, str_a_i2p, strf_r8p, strf_i4p, str_a_i4p, str_i8p, strf_i1p, str_a_r4p, str_r4p, str_i1p, str_i4p, str_r8p, str_a_i1p, strf_i8p, str_a_i8p, strf_i2p, str_bol, str_a_r8p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
str_a_i1p calls str_i1p
str_a_i8p calls str_i8p
str_a_r8p calls str_r8p
test_all calls bcton