test_all – HASTY
test_all Program
18 statements
Source File
Uses:
penf
iso_fortran_env
PENF's testing program.
Usage
 ./test_all
Calls
Source Code
test_all
Source Code
program test_all
!-----------------------------------------------------------------------------------------------------------------------------------
!< PENF's testing program.
!<
!<### Usage
!<```bash
!< ./test_all
!<```
!-----------------------------------------------------------------------------------------------------------------------------------
use penf
use, intrinsic :: ISO_FORTRAN_ENV, only : stdout=>OUTPUT_UNIT
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
call penf_init
call penf_print(unit=stdout)
print "(A)", ''
print "(A)", 'Testing IR_Precision tools'
print "(A)", 'Casting real-to-string: '//str(n=1._R8P)
print "(A)", 'Casting integer-to-string: '//str(n=11_I8P)
print "(A,"//FR8P//")", 'Casting string-to-real: ',cton(str='2.2d0', knd=1._R8P)
print "(A,"//FI4P//")", 'Casting integer-to-string: ',cton(str='43', knd=1_I4P)
print "(A)", 'Casting integer-to-string with zero padding: '//trim(strz(nz_pad=3, n=34_I8P))
#ifndef __GFORTRAN__
print "(A)", 'Casting real-to-bit_string: '//bstr(n=1._R4P)
#endif
print "(A)", 'Casting integer-to-bit_string: '//bstr(n=1_I4P)
#ifndef __GFORTRAN__
print "(A,"//FR4P//")", 'Casting bit_string-to-real: ', bcton(bstr='00111111100000000000000000000000', knd=1._R4P)
#endif
print "(A,"//FI4P//")", 'Casting bit_string-to-integer: ',bcton(bstr='00000000000000000000000000000001', knd=1_I4P)
print "(A)", 'Number of digit of 1023: '//str(n=digit(1023_I4P))
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram test_all
All Programs
compact_real hasty_test_caf_basic hasty_test_caf_get_clone hasty_test_dictionary hasty_test_hash_table hasty_test_hash_table_homo hasty_test_hash_table_homocontent_failure hasty_test_hash_table_homokey_failure test_all test_tester_1 test_tester_2 test_tester_3 test_tester_4
Call graph
test_all calls str, bcton, strz, digit, cton, penf_init, bstr, penf_print
str calls str_a_r8p, strf_i4p, str_a_i8p, strf_i1p, strf_i2p, str_r4p, str_a_i1p, str_i8p, str_i1p, strf_i8p, str_a_i2p, str_bol, str_a_r4p, strf_r8p, str_i4p, str_i2p, strf_r4p, str_a_i4p, str_r8p
bcton calls bctoi_i1p, bctor_r4p, bctoi_i8p, bctoi_i4p, bctoi_i2p, bctor_r8p
strz calls strz_i2p, strz_i8p, strz_i1p, strz_i4p
digit calls digit_i8, digit_i2, digit_i1, digit_i4
cton calls ctor_r8p, ctoi_i2p, ctor_r4p, ctoi_i1p, ctoi_i8p, ctoi_i4p
penf_init calls check_endian
bstr calls bstr_r8p, bstr_i2p, bstr_i1p, bstr_i8p, bstr_r4p, bstr_i4p
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
str_r4p calls compact_real_string
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_r4p calls str_r4p
str_a_i4p calls str_i4p
str_r8p calls compact_real_string
bctoi_i1p calls str
bctor_r4p calls str
bctoi_i8p calls str
bctoi_i4p calls str
bctoi_i2p calls str
bctor_r8p calls str